import Phaser from 'phaser';
export declare class MainScene extends Phaser.Scene {
    private levelIndex;
    private mode;
    private players;
    private enemies;
    private walls;
    private coins;
    private exit;
    private decorations;
    private hudStats?;
    private levelBanner?;
    private waitingText?;
    private endText?;
    private rulesLayer?;
    private rulesOpen;
    private runActive;
    private runOutcome;
    private coinsRemaining;
    private levelCoinsCollected;
    private totalRunCoins;
    private lives;
    private currentMap;
    private hitCooldownUntil;
    private readonly startHandler;
    constructor();
    create(): void;
    update(time: number): void;
    private startRun;
    private loadLevel;
    private createExit;
    private createPlayers;
    private createEnemies;
    private collectCoin;
    private tryCompleteLevel;
    private onPlayerCaught;
    private finishRun;
    private updatePlayers;
    private updateEnemies;
    private findClosestPlayer;
    private findPath;
    private rebuildPath;
    private isWalkable;
    private worldToTile;
    private tileToWorld;
    private updateHudText;
    private toggleRules;
    private buildRulesOverlay;
    private clearLevel;
}
//# sourceMappingURL=MainScene.d.ts.map